# from https://github.com/oprypin/mkdocs-gen-files/blob/master/mkdocs.yml
site_name: "Name of your Project"
site_description: "You Mk docs Site"
copyright: Copyright &copy; 2025 Your Company
# site_url: "https://oprypin.github.io/mkdocs-gen-files" # TODO: fill out
# repo_url: "https://github.com/oprypin/mkdocs-gen-files" # TODO: fill out

nav:
  - Intro: index.md
  - Code Reference: reference/

theme:
  name: material
  features:
    - content.action.edit
    - navigation.tabs
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: teal
    accent: purple

extra_css:
  - assets/style.css

watch:
  - src

plugins:
  - search
  - gen-files:
      scripts:
        - docs/mkdocs_scripts/gen_pages.py
  - literate-nav
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            show_root_heading: true
            show_signature_annotations: true
            show_source: false

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - !relative $config_dir
  - admonition
  - def_list
  - toc:
      permalink: "#"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  nav:
    absolute_links: ignore
