# name: mkdocs
# 
# on: push
# 
# env:
#   PYTEST_ON_CI: True
# 
# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v4
# 
#       - name: Install uv
#         uses: astral-sh/setup-uv@v5
# 
#       - name: "Set up Python"
#         uses: actions/setup-python@v5
#         with:
#           python-version-file: "pyproject.toml"
# 
#       - name: Install dependencies
#         run: uv sync --all-groups --frozen
# 
#       - name: set PY
#         run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
# 
#       - name: Conditional Deployment
#         run: |
#           if [ "${{ github.ref_name }}" = "main" ]; then
#             uv run mkdocs gh-deploy --force
#           else
#             uv run mkdocs build
#           fi